[tool.towncrier]
package = "action"
filename = "CHANGELOG.md"
directory = "changelog/"
start_string = "<!-- towncrier release notes start -->\n"
underlines = ["", "", ""]
template = "changelog/template.jinja"
title_format = "## [{version}](https://github.com/alcarney/action/tree/{version}) - {project_date}"
issue_format = "[#{issue}](https://github.com/alcarney/action/issues/{issue})"
