[tool.towncrier]
package = "action"
filename = "CHANGELOG.rst"
directory = "changelog/"
title_format = "{version} - {project_date}"
issue_format = "`{issue} <https://github.com/swyddfa/arlunio/issues/{issue}>`_"
