name: Create Release

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get Build Number
      uses: einaregilsson/build-number@v1
      with:
        token: ${{secrets.github_token}}
      if: github.ref == 'refs/heads/develop'

    - name: Set Version Number
      shell: bash
      run : |
        sed -i 's/"\(.*\)"/"\1b'"${BUILD_NUMBER}"'"/' action/_version.py
        cat action/_version.py
      if: github.ref == 'refs/heads/develop'

    - name: Export version
      id: info
      run: |
         version=$(sed 's/.*"\(.*\)".*/\1/' action/_version.py)
         release_date=$(date +%Y-%m-%d)

         echo "::set-env name=VERSION::$version"
         echo "::set-output name=VERSION::$version"

         echo "::set-env name=RELEASE_DATE::$release_date"
         echo "::set-output name=RELEASE_DATE::$release_date"

    - name: Print version
      run: |
        echo $VERSION

    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup Environment
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Build package
      run: |
        tox -e pkg

    - name: Export Assets
      id: pkg
      run: |
        whl=$(find dist/ -name '*.whl' -exec basename {} \;)
        echo "::set-output name=WHL::$whl"

        src=$(find dist/ -name '*.tar.gz' -exec basename {} \;)
        echo "::set-output name=SRC::$src"

      # Based on: https://itnext.io/creating-a-github-action-to-tag-commits-2722f1560dec
    - name: Create Tag
      run: |
        commit=$(git rev-parse HEAD)

        # POST a new ref to repo via Github API
        curl -s -X POST https://api.github.com/repos/alcarney/action/git/refs \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOF
        {
          "ref": "refs/tags/v$VERSION",
          "sha": "$commit"
        }
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.info.outputs.VERSION }}
        release_name: v${{ steps.info.outputs.VERSION}} - ${{ steps.info.outputs.RELEASE_DATE }}
        draft: false
        prerelease: ${{ github.ref == 'refs/heads/develop' }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/${{ steps.pkg.outputs.WHL }}
        asset_name: ${{ steps.pkg.outputs.WHL }}
        asset_content_type: application/octet-stream

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/${{ steps.pkg.outputs.SRC }}
        asset_name: ${{ steps.pkg.outputs.SRC }}
        asset_content_type: application/octet-stream

    - name: Upload Release Notes
      shell: bash
      run: |
        python -m pip install towncrier docutils

        ./scripts/write-release-notes.sh > release-notes.html
        notes=$(cat release-notes.html)

        echo $notes

        curl -s -X PATCH https://api.github.com/repos/alcarney/action/releases/${{ steps.release.outputs.id }} \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOF
        {
          "body": "$notes"
        }
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
