name: Create Release

on:
  push:
    branches:
    -

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade towncrier tox
      name: Setup Environment

    - name: Export version
      id: info
      run: |
         version=$(sed 's/.*"\(.*\)".*/\1/' action/_version.py)
         release_date=$(date +%Y-%m-%d)

         echo "VERSION=$version" >> $GITHUB_ENV
         echo "RELEASE_DATE=$release_date" >> $GITHUB_ENV

    - name: Print version
      run: |
        echo $VERSION

    - name: Build package
      run: |
        tox -e pkg

    - run: |
        # Setup git, commit, tag and push all the changes.
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        # Other stages may have run before this, make sure we have the latest
        git pull --rebase origin release
        git tag -a "v${VERSION}" -m "v${VERSION}"

        git push origin release
        git push origin --tags

        gh release create --target "v${VERSION}" ./dist/*
      name: Create Release

